name: node_js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [16]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: npm install

    - name: Pre-Tests setup
      run: npm i -g gatsby

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3

    - name: Build
      run: ACTIVE_ENV=github npm run build
